name: Build

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        extension_support: [0, 1]
   
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Ubuntu 
      if: matrix.os == 'ubuntu-latest'
      run: | 
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo apt-get install -y build-essential
        sudo apt-get install -y python3-dev python3-pip python3-virtualenv
        sudo apt-get install -y pkg-config libssl-dev libdbus-1-dev libdbus-glib-1-dev python-dbus libffi-dev libkrb5-dev

    - name: Install dependencies
      run: |
        pip install external/okta-0.0.3.1-py2.py3-none-any.whl
        pip install -e .
        pip install -e .[test]
        pip install -e .[setup]
    - name: Create build
      env:
        UST_EXTENSION: ${{ matrix.extension_support }}
      run: make
    - name: Test with pytest
      run: pytest
