name: Build

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ '**'  ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest]
        extension_support: [0, 1]

    steps:
    - uses: actions/checkout@v7

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'
    - name: Ubuntu dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config \
                                libssl-dev libdbus-1-dev libdbus-glib-1-dev libffi-dev libkrb5-dev

    - name: Install dependencies
      run: |
        pip install ./sign_client
        pip install external/okta-0.0.3.1-py2.py3-none-any.whl
        pip install -e .
        pip install -e .[test]
        pip install -e .[setup]
    - name: Create build
      env:
        UST_EXTENSION: ${{ matrix.extension_support }}
      run: make
    - name: Test with pytest
      run: pytest
